"""add_user_roles_and_ai_review_notes

Revision ID: 1f8953f132e9
Revises: 3afa6a0032c2
Create Date: 2026-03-01 15:56:07.451132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1f8953f132e9'
down_revision: Union[str, Sequence[str], None] = '3afa6a0032c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('ai_review_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.drop_column('application', 'ai_review_notes')
    # ### end Alembic commands ###
