"""Add business application models

Revision ID: 3afa6a0032c2
Revises: c6a1ab37c2b2
Create Date: 2026-02-22 16:42:22.257733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3afa6a0032c2'
down_revision: Union[str, Sequence[str], None] = 'c6a1ab37c2b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('legal_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('license_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trade_name_1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trade_name_2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trade_name_3', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activities', sa.JSON(), nullable=True),
    sa.Column('jurisdiction', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('free_zone_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('wait_for_ejari', sa.Boolean(), nullable=True),
    sa.Column('ejari_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('package_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stakeholder',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('middle_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nationality', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uae_resident', sa.Boolean(), nullable=False),
    sa.Column('passport_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('passport_expiry_date', sa.Date(), nullable=True),
    sa.Column('emirates_id_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unified_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_ubo', sa.Boolean(), nullable=False),
    sa.Column('ownership_percentage', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('stakeholder_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['stakeholder_id'], ['stakeholder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document')
    op.drop_table('stakeholder')
    op.drop_table('application')
    # ### end Alembic commands ###
