"""Add AI Review Tracking

Revision ID: 8ed1270853fb
Revises: 1f8953f132e9
Create Date: 2026-03-08 06:00:49.429174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8ed1270853fb'
down_revision: Union[str, Sequence[str], None] = '1f8953f132e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('ai_review_summary', sa.JSON(), nullable=True))
    op.add_column('document', sa.Column('review_status', sqlmodel.sql.sqltypes.AutoString(), server_default='uploaded', nullable=False))
    op.add_column('document', sa.Column('raw_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('document', sa.Column('document_type_detected', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('document', sa.Column('processed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'processed_at')
    op.drop_column('document', 'document_type_detected')
    op.drop_column('document', 'raw_text')
    op.drop_column('document', 'review_status')
    op.drop_column('application', 'ai_review_summary')
    # ### end Alembic commands ###
